---
title: "Power analysis Type"
author: "Lokesh Mano"
date: last-modified
format:
  html:
    embed-resources: true
    self-contained-math: true
    toc: true
    toc-location: left
    cap-location: top
    fig-cap-location: top
    code-fold: true
    code-tools: true
    mainfont: "Baskerville"
    font-size: 12
---

```{r}
#| label: raw 
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center
#| echo: false

library(ggplot2)
library(phyloseq)
library(dplyr)
library(tidyverse)
library(plotly)

theme_set(theme_bw())
set.seed(100)

setwd("/workspaces/7993_Mic_Psori/results/stats")
sample_info <- read.table("../../data/sample_md.tsv", header = T, sep = "\t", check.names = F)
row.names(sample_info) <- sample_info$SampleID

sample_info$Type <- factor(sample_info$Type, levels = c("control", "pso_nonlesional", "pso_lesional"))
sample_info$Gender <- as.factor(sample_info$Gender)

sample_info <- sample_info %>% mutate(PsoTreatment = replace(PsoTreatment, PsoTreatment == "0", "None"))
sample_info$PsoTreatment <- factor(sample_info$PsoTreatment, levels = c("None", "Moisturizer", "TopicalSteroids"))

sample_info$PASISeverity <- as.factor(sample_info$PASISeverity)
sample_info <- sample_info %>% 
  mutate(PASISeverity = case_when(
    PASISeverity == "0" ~ "None",
    PASISeverity == "1" ~ "Low",
    PASISeverity == "2" ~ "Medium",
    PASISeverity == "3" ~ "High",
    TRUE ~ PASISeverity))
sample_info$PASISeverity <- factor(sample_info$PASISeverity, levels = c("None", "Low", "Medium", "High"))

sample_info$TypeSeverity <- factor(sample_info$TypeSeverity, 
  levels = c("control_0", "pso_nonlesional_1", "pso_nonlesional_2", "pso_nonlesional_3",
  "pso_lesional_1", "pso_lesional_2", "pso_lesional_3"))

sample_info <- sample_info %>% mutate(PrevSysTreatmentPso = replace(PrevSysTreatmentPso, PrevSysTreatmentPso == "", "None"))
sample_info$PrevSysTreatmentPso <- factor(sample_info$PrevSysTreatmentPso, levels = c("None", "No", "Yes"))

sample_info$AntiinflamMedication <- as.factor(sample_info$AntiinflamMedication)
sample_info$SSRI <- as.factor(sample_info$SSRI)
sample_info$OtherMedication <- as.factor(sample_info$OtherMedication)
sample_info$DiabetesHypertensionHyperlipidemia <- as.factor(sample_info$DiabetesHypertensionHyperlipidemia)

sample_info <- sample_info %>% 
  mutate(OtherDiseases = case_when(
    OtherDiseases == "" ~ NA,
    OtherDiseases == "0" ~ "None",
    TRUE ~ OtherDiseases))
sample_info$OtherDiseases <- as.factor(sample_info$OtherDiseases)

sample_info <- sample_info %>% mutate(SmokingSnuff = replace(SmokingSnuff, SmokingSnuff == "0", "None"))
sample_info$SmokingSnuff <- as.factor(sample_info$SmokingSnuff)

sample_info$Alcohol <- as.factor(sample_info$Alcohol)
sample_info <- sample_info %>% 
  mutate(Alcohol = case_when(
    Alcohol == "0" ~ "None",
    Alcohol == "1" ~ "Low",
    Alcohol == "2" ~ "Medium",
    Alcohol == "3" ~ "High",
    Alcohol == "4" ~ "VeryHigh",
    TRUE ~ Alcohol))
sample_info$Alcohol <- factor(sample_info$Alcohol, levels = c("None", "Low", "Medium", "High", "VeryHigh"))

sample_info <- sample_info %>% 
  mutate(Arthritis = case_when(
    Arthritis == "" ~ NA,
    Arthritis == "0" ~ "None",
    TRUE ~ Arthritis))
sample_info$Arthritis <- as.factor(sample_info$Arthritis)

sample_info <- sample_info %>% mutate(Location = replace(Location, Location == "", NA))
sample_info$Location <- as.factor(sample_info$Location)

lulu_otu_table <- read.table("../lulu_otu_table.tsv", header = T, row.names = 1, sep = "\t")

taxa_info <- read.table("../processed_taxa.tsv", header = 1, row.names = 1, sep = "\t")
taxa_info <- as.matrix(taxa_info)

OTU = otu_table(lulu_otu_table, taxa_are_rows = TRUE)
TAX = tax_table(taxa_info)
META = sample_data(sample_info)

psor_psq_raw = phyloseq(OTU, TAX, META)
psor_psq_raw
sum(otu_table(psor_psq_raw))
```

```{r}
#| label: filt 
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center
#| echo: false

main_taxa <- c("Bacteria", "Archaea")
psor_psq_tFilt <- subset_taxa(psor_psq_raw, Kingdom %in% main_taxa)
psor_psq_tcFilt <- filter_taxa(psor_psq_tFilt, function(x) sum(x > 5) > (0.1*length(x)), TRUE)
psor_psq_filt <- subset_taxa(psor_psq_tcFilt, Family != "Mitochondria")

psor_psq_filt
sum(otu_table(psor_psq_filt))
```

```{r}
#| label: addspe 
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center
#| echo: false

add_spe <- read.table("../ampliseq_16S_output/dada2/ASV_tax_species.silva_138_2.tsv", header = 1, sep = "\t")
spe_exact <- add_spe %>%
  select(ASV_ID, Genus, Species_exact, confidence) %>%
  filter(Species_exact != "") %>%
  filter(confidence > 0.75) %>%
  mutate(Species_exact = paste0(Genus, '_', Species_exact)) %>%
  select(ASV_ID, Species_exact)

taxa_new <- tax_table(psor_psq_filt) %>% 
  as.data.frame() %>%
  rownames_to_column('ASV_ID') %>%
  left_join(spe_exact) %>%
  mutate(Species = ifelse(is.na(Species_exact),
    Species, Species_exact)) %>%
  select(-Species_exact)

row.names(taxa_new) <- taxa_new$ASV_ID
taxa_new$ASV_ID <- NULL
taxa_new <- as.matrix(taxa_new)
tax_table(psor_psq_filt) <- tax_table(taxa_new)

known_species <- taxa_new %>%
  as.data.frame() %>%
  rownames_to_column("ASV_ID") %>%
  filter(!grepl("nclass", Species)) 

known_species_asv_ids <- known_species %>%
  pull(ASV_ID)

known_genus <- taxa_new %>%
  as.data.frame() %>%
  rownames_to_column("ASV_ID") %>%
  filter(!grepl("nclass", Genus))

known_genus_asv_ids <- known_genus %>%
  pull(ASV_ID)

known_genus %>%
  pull(Genus) %>%
  n_distinct()

known_species %>%
  pull(Species) %>%
  n_distinct()
```

```{r}
#| label: gen-spe tables 
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center

gen_psq <- prune_taxa(psor_psq_filt, taxa = known_genus_asv_ids)
sum(otu_table(gen_psq))

spe_psq <- prune_taxa(psor_psq_filt, taxa = known_species_asv_ids)
sum(otu_table(spe_psq))

gen_glom_psq <- tax_glom(gen_psq, "Genus")
spe_glom_psq <- tax_glom(spe_psq, "Species")

```

```{r}
#| label: micr-sort
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center

snp_filt <- read.table("../snp_filtered_ordered.tsv", row.names = 1, header = T)
low.count.removal <- function(
                        data, # OTU count df of size n (sample) x p (OTU)
                        percent=0.01 # cutoff chosen
                        ){
    keep.otu = which(colSums(data)*100/(sum(colSums(data))) > percent)
    data.filter = data[,keep.otu]
    return(list(data.filter = data.filter, keep.otu = keep.otu))
}

spe_lei <- subset_samples(spe_glom_psq, SampleID %in% row.names(snp_filt))
taxa_info <- as.data.frame(tax_table(spe_lei))
mic.raw <- as.data.frame(t(otu_table(spe_lei)))
names(mic.raw) <- taxa_info$Species
mic.offset <- mic.raw+1
result.filter <- low.count.removal(mic.offset, percent=0.01)
mic.filter <- result.filter$data.filter
length(result.filter$keep.otu) 
```

```{r}
#| label: micr-samp
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center

library(mixOmics)
set.seed(100)

lib.size <- apply(mic.filter, 1, sum) # determine total count for each sample
barplot(lib.size) # and plot as bar plot
mic.filter <- mic.filter[which(lib.size < 200000 & lib.size > 15000),]
mic.clr <- logratio.transfo(as.matrix(mic.filter), 
                             logratio = 'CLR', offset = 0)
```

```{r}
#| label: snp-sort
#| warning: false
#| message: false
#| include: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center

snp.filt <- snp_filt[which(row.names(snp_filt) %in% row.names(mic.clr)), ]
snp.filt <- snp.filt[order(row.names(snp.filt)), ]
mic.clr <- mic.clr[order(row.names(mic.clr)), ]

sample_info_ord <- snp.filt %>% 
  as.data.frame() %>%
  rownames_to_column('SampleID') %>%
  dplyr::select(SampleID) %>%
  left_join(sample_info) %>% 
  column_to_rownames(var = "SampleID")
```

# Multipower

```{r}
dim(mic.clr)
```

## FDR 0.1

```{r}
#| label: multipower
#| warning: false
#| message: false
#| fig-height: 10
#| fig-width: 20
#| fig-dpi: 400
#| fig-align: center

library(MultiPower)
library(FDRsampsize)



set.seed(100)
X <- list(mic = t(mic.clr),
          snp = t(snp.filt))
Y <- list(mic = droplevels(sample_info_ord$Type),
          snp = droplevels(sample_info_ord$Type))
Z <- c(2,2)

P <- MultiPower(X, Y, Z, omicPower = 0.6, averagePower = 0.85, null.effect = 0, fdr = 0.1, cost = 1, equalSize = TRUE, max.size = 2000, omicCol = NULL, powerPlots = TRUE)

P$data2plot
```

## FDR 0.05


```{r}
P <- MultiPower(X, Y, Z, omicPower = 0.6, averagePower = 0.85, null.effect = 0, fdr = 0.05, cost = 1, equalSize = TRUE, max.size = 20000, omicCol = NULL, powerPlots = TRUE)

P$data2plot
```